"""add settings table and event preorder defaults

Revision ID: 6c27d8f0f0b1
Revises: 9a840c05a7b1
Create Date: 2026-08-28 15:57:24.102212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c27d8f0f0b1'
down_revision: Union[str, None] = '9a840c05a7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.add_column('events', sa.Column('preorder_default_date', sa.String(length=20), nullable=True))
    op.add_column('events', sa.Column('preorder_default_time_start', sa.String(length=5), nullable=True))
    op.add_column('events', sa.Column('preorder_default_time_end', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'preorder_default_time_end')
    op.drop_column('events', 'preorder_default_time_start')
    op.drop_column('events', 'preorder_default_date')
    op.drop_table('settings')
    # ### end Alembic commands ###
