"""add customer email and pickup time to transactions

Revision ID: 9a840c05a7b1
Revises: d1bccc66d94f
Create Date: 2026-08-28 15:17:02.382371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9a840c05a7b1'
down_revision: Union[str, None] = 'd1bccc66d94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('customer_email', sa.String(length=254), nullable=True))
    op.add_column('transactions', sa.Column('pickup_time_start', sa.String(length=5), nullable=True))
    op.add_column('transactions', sa.Column('pickup_time_end', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'pickup_time_end')
    op.drop_column('transactions', 'pickup_time_start')
    op.drop_column('transactions', 'customer_email')
    # ### end Alembic commands ###
